//
// Copyright (c) Lander Vanroye, KU Leuven
//
// Tests for the v0-compatible C interface (used by CasADi).
//
#include "fatrop/ocp/OCPCInterface.h"
#include <gtest/gtest.h>

namespace
{
    // ---------------------------------------------------------------------------
    // Single-stage problem (K = 1), as generated by CasADi for an Opti problem
    // without dynamics: min (u - 3)^2 with a single variable.
    // There are no dynamics blocks at all in this case.
    // ---------------------------------------------------------------------------
    fatrop_int single_get_nx(fatrop_int, void *) { return 0; }
    fatrop_int single_get_nu(fatrop_int, void *) { return 1; }
    fatrop_int single_get_ng(fatrop_int, void *) { return 0; }
    fatrop_int single_get_ng_ineq(fatrop_int, void *) { return 0; }
    fatrop_int single_get_horizon_length(void *) { return 1; }

    fatrop_int single_eval_RSQrqt(const double *objective_scale, const double *inputs_k,
                                  const double *, const double *, const double *, const double *,
                                  const double *, const double *, struct blasfeo_dmat *res,
                                  fatrop_int, void *)
    {
        // (nu + nx + 1) x (nu + nx) = 2 x 1
        blasfeo_dgein1(2. * *objective_scale, res, 0, 0);
        blasfeo_dgein1(2. * (inputs_k[0] - 3.) * *objective_scale, res, 1, 0);
        return 0;
    }
    fatrop_int single_eval_rq(const double *objective_scale, const double *inputs_k, const double *,
                              const double *, const double *, double *res, fatrop_int, void *)
    {
        res[0] = 2. * (inputs_k[0] - 3.) * *objective_scale;
        return 0;
    }
    fatrop_int single_eval_L(const double *objective_scale, const double *inputs_k, const double *,
                             const double *, const double *, double *res, fatrop_int, void *)
    {
        res[0] = (inputs_k[0] - 3.) * (inputs_k[0] - 3.) * *objective_scale;
        return 0;
    }

    // ---------------------------------------------------------------------------
    // Two-stage problem (K = 2), exercising the dynamics blocks:
    //   min  u0^2 + (x1 - 3)^2   s.t.  x1 = x0 + u0,  x0 = 1
    // Stage 0 has (nu, nx) = (1, 1) and one equality constraint fixing x0,
    // stage 1 has (nu, nx) = (0, 1). The optimum is u0 = 1, x1 = 2.
    // ---------------------------------------------------------------------------
    fatrop_int two_get_nx(fatrop_int, void *) { return 1; }
    fatrop_int two_get_nu(fatrop_int k, void *) { return k == 0 ? 1 : 0; }
    fatrop_int two_get_ng(fatrop_int k, void *) { return k == 0 ? 1 : 0; }
    fatrop_int two_get_ng_ineq(fatrop_int, void *) { return 0; }
    fatrop_int two_get_horizon_length(void *) { return 2; }

    fatrop_int two_eval_BAbt(const double *states_kp1, const double *inputs_k,
                             const double *states_k, const double *, const double *,
                             struct blasfeo_dmat *res, fatrop_int, void *)
    {
        // (nu + nx + 1) x nx_next = 3 x 1: [B; A; b] with b = f(x, u) - x_next
        blasfeo_dgein1(1., res, 0, 0);
        blasfeo_dgein1(1., res, 1, 0);
        blasfeo_dgein1(states_k[0] + inputs_k[0] - states_kp1[0], res, 2, 0);
        return 0;
    }
    fatrop_int two_eval_b(const double *states_kp1, const double *inputs_k, const double *states_k,
                          const double *, const double *, double *res, fatrop_int, void *)
    {
        res[0] = states_k[0] + inputs_k[0] - states_kp1[0];
        return 0;
    }
    fatrop_int two_eval_Ggt(const double *, const double *states_k, const double *, const double *,
                            struct blasfeo_dmat *res, fatrop_int k, void *)
    {
        if (k != 0)
            return 0;
        // (nu + nx + 1) x ng = 3 x 1: [dg/du; dg/dx; g] for g = x0 - 1
        blasfeo_dgein1(0., res, 0, 0);
        blasfeo_dgein1(1., res, 1, 0);
        blasfeo_dgein1(states_k[0] - 1., res, 2, 0);
        return 0;
    }
    fatrop_int two_eval_g(const double *, const double *states_k, const double *, const double *,
                          double *res, fatrop_int k, void *)
    {
        if (k == 0)
            res[0] = states_k[0] - 1.;
        return 0;
    }
    fatrop_int two_eval_RSQrqt(const double *objective_scale, const double *inputs_k,
                               const double *states_k, const double *, const double *,
                               const double *, const double *, const double *,
                               struct blasfeo_dmat *res, fatrop_int k, void *)
    {
        if (k == 0)
        {
            // 3 x 2, variables ordered as (u, x); only u0^2 contributes
            blasfeo_dgein1(2. * *objective_scale, res, 0, 0);
            blasfeo_dgein1(0., res, 0, 1);
            blasfeo_dgein1(0., res, 1, 0);
            blasfeo_dgein1(0., res, 1, 1);
            blasfeo_dgein1(2. * inputs_k[0] * *objective_scale, res, 2, 0);
            blasfeo_dgein1(0., res, 2, 1);
        }
        else
        {
            // 2 x 1
            blasfeo_dgein1(2. * *objective_scale, res, 0, 0);
            blasfeo_dgein1(2. * (states_k[0] - 3.) * *objective_scale, res, 1, 0);
        }
        return 0;
    }
    fatrop_int two_eval_rq(const double *objective_scale, const double *inputs_k,
                           const double *states_k, const double *, const double *, double *res,
                           fatrop_int k, void *)
    {
        if (k == 0)
        {
            res[0] = 2. * inputs_k[0] * *objective_scale;
            res[1] = 0.;
        }
        else
        {
            res[0] = 2. * (states_k[0] - 3.) * *objective_scale;
        }
        return 0;
    }
    fatrop_int two_eval_L(const double *objective_scale, const double *inputs_k,
                          const double *states_k, const double *, const double *, double *res,
                          fatrop_int k, void *)
    {
        if (k == 0)
            res[0] = inputs_k[0] * inputs_k[0] * *objective_scale;
        else
            res[0] = (states_k[0] - 3.) * (states_k[0] - 3.) * *objective_scale;
        return 0;
    }

    // ---------------------------------------------------------------------------
    // Callbacks shared by both problems.
    // ---------------------------------------------------------------------------
    fatrop_int no_params_k(fatrop_int, void *) { return 0; }
    fatrop_int no_params(void *) { return 0; }
    fatrop_int no_op_eval_BAbt(const double *, const double *, const double *, const double *,
                               const double *, struct blasfeo_dmat *, fatrop_int, void *)
    {
        return 0;
    }
    fatrop_int no_op_eval_Ggt(const double *, const double *, const double *, const double *,
                              struct blasfeo_dmat *, fatrop_int, void *)
    {
        return 0;
    }
    fatrop_int no_op_eval_b(const double *, const double *, const double *, const double *,
                            const double *, double *, fatrop_int, void *)
    {
        return 0;
    }
    fatrop_int no_op_eval_g(const double *, const double *, const double *, const double *,
                            double *, fatrop_int, void *)
    {
        return 0;
    }
    fatrop_int no_op_bounds(double *, double *, fatrop_int, void *) { return 0; }
    fatrop_int zero_initial(double *, fatrop_int, void *) { return 0; }

    // CasADi always installs the "full evaluation" callbacks. Returning 0 means
    // "fall back to the stage-wise callbacks", which is what CasADi does when it
    // cannot evaluate the whole horizon in one go.
    fatrop_int full_eval_lag_hess(double, const double *, const double *, const double *,
                                  const double *, struct blasfeo_dmat *,
                                  const struct FatropOcpCDims *, void *)
    {
        return 0;
    }
    fatrop_int full_eval_constr_jac(const double *, const double *, const double *,
                                    struct blasfeo_dmat *, struct blasfeo_dmat *,
                                    struct blasfeo_dmat *, const struct FatropOcpCDims *, void *)
    {
        return 0;
    }
    fatrop_int full_eval_contr_viol(const double *, const double *, const double *, double *,
                                    const struct FatropOcpCDims *, void *)
    {
        return 0;
    }
    fatrop_int full_eval_obj_grad(double, const double *, const double *, const double *, double *,
                                  const struct FatropOcpCDims *, void *)
    {
        return 0;
    }
    fatrop_int full_eval_obj(double, const double *, const double *, const double *, double *,
                             const struct FatropOcpCDims *, void *)
    {
        return 0;
    }

    FatropOcpCInterface make_interface()
    {
        FatropOcpCInterface ocp = {};
        ocp.get_n_stage_params = no_params_k;
        ocp.get_n_global_params = no_params;
        ocp.eval_BAbt = no_op_eval_BAbt;
        ocp.eval_Ggt = no_op_eval_Ggt;
        ocp.eval_Ggt_ineq = no_op_eval_Ggt;
        ocp.eval_b = no_op_eval_b;
        ocp.eval_g = no_op_eval_g;
        ocp.eval_gineq = no_op_eval_g;
        ocp.get_bounds = no_op_bounds;
        ocp.get_initial_xk = zero_initial;
        ocp.get_initial_uk = zero_initial;
        ocp.full_eval_lag_hess = full_eval_lag_hess;
        ocp.full_eval_constr_jac = full_eval_constr_jac;
        ocp.full_eval_contr_viol = full_eval_contr_viol;
        ocp.full_eval_obj_grad = full_eval_obj_grad;
        ocp.full_eval_obj = full_eval_obj;
        return ocp;
    }
} // namespace

// A single-stage problem has no dynamics blocks at all. Filling the buffers used
// to run over the full horizon, reading one element past the end of the vector of
// dynamics Jacobians (github.com/meco-group/fatrop/issues/58).
TEST(CInterfaceTest, SingleStageProblem)
{
    FatropOcpCInterface ocp = make_interface();
    ocp.get_nx = single_get_nx;
    ocp.get_nu = single_get_nu;
    ocp.get_ng = single_get_ng;
    ocp.get_ng_ineq = single_get_ng_ineq;
    ocp.get_horizon_length = single_get_horizon_length;
    ocp.eval_RSQrqt = single_eval_RSQrqt;
    ocp.eval_rq = single_eval_rq;
    ocp.eval_L = single_eval_L;

    FatropOcpCSolver *solver = fatrop_ocp_c_create(&ocp, nullptr, nullptr);
    ASSERT_NE(solver, nullptr);
    fatrop_ocp_c_set_option_int(solver, "print_level", 0);
    EXPECT_EQ(fatrop_ocp_c_solve(solver), 0);

    const blasfeo_dvec *primal = fatrop_ocp_c_get_primal(solver);
    EXPECT_NEAR(BLASFEO_DVECEL(const_cast<blasfeo_dvec *>(primal), 0), 3., 1e-6);
    fatrop_ocp_c_destroy(solver);
}

TEST(CInterfaceTest, TwoStageProblemWithDynamics)
{
    FatropOcpCInterface ocp = make_interface();
    ocp.get_nx = two_get_nx;
    ocp.get_nu = two_get_nu;
    ocp.get_ng = two_get_ng;
    ocp.get_ng_ineq = two_get_ng_ineq;
    ocp.get_horizon_length = two_get_horizon_length;
    ocp.eval_BAbt = two_eval_BAbt;
    ocp.eval_b = two_eval_b;
    ocp.eval_Ggt = two_eval_Ggt;
    ocp.eval_g = two_eval_g;
    ocp.eval_RSQrqt = two_eval_RSQrqt;
    ocp.eval_rq = two_eval_rq;
    ocp.eval_L = two_eval_L;

    FatropOcpCSolver *solver = fatrop_ocp_c_create(&ocp, nullptr, nullptr);
    ASSERT_NE(solver, nullptr);
    fatrop_ocp_c_set_option_int(solver, "print_level", 0);
    EXPECT_EQ(fatrop_ocp_c_solve(solver), 0);

    // primal ordering is (u0, x0, x1)
    blasfeo_dvec *primal = const_cast<blasfeo_dvec *>(fatrop_ocp_c_get_primal(solver));
    EXPECT_NEAR(BLASFEO_DVECEL(primal, 0), 1., 1e-6);
    EXPECT_NEAR(BLASFEO_DVECEL(primal, 1), 1., 1e-6);
    EXPECT_NEAR(BLASFEO_DVECEL(primal, 2), 2., 1e-6);
    fatrop_ocp_c_destroy(solver);
}
